version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend_service
    ports:
      - "3001:3001"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    restart: always
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

volumes:
  ollama_data: {}
